# Generated by Django 2.2.24 on 2025-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20250502_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=None, verbose_name='Новостройка'),
        ),
    ]
