# Generated by Django 2.2.24 on 2025-05-02 09:56

from django.db import migrations


def change_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20250502_1148'),
    ]

    operations = [
        migrations.RunPython(change_new_building)
    ]
