# Generated by Django 2.2.24 on 2025-05-02 14:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250502_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_fone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Номер телефона'),
        ),
    ]
