# Generated by Django 2.2.24 on 2025-05-02 15:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_owner_pure_fone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_fone',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Номер владельца'),
        ),
    ]
