# Generated by Django 2.2.24 on 2025-05-02 15:37

from django.db import migrations
import phonenumbers


def change_phone_number(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    
    for flat in flats:
        phone_number = flat.owners_phonenumber
        flat.owner_pure_phone = get_correct_phone_number(phone_number)
        flat.save()
        
        
def get_correct_phone_number(phone_number):
    
    if not phone_number:
        return None
    
    number_info = phonenumbers.parse(phone_number, "RU")
    clear_phone_number = phonenumbers.format_number(number_info, phonenumbers.PhoneNumberFormat.E164)
    return clear_phone_number
        

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20250502_1829'),
    ]

    operations = [
        migrations.RunPython(change_phone_number)
    ]
