# Generated by Django 2.2.24 on 2025-05-02 17:12

from django.db import migrations
import phonenumbers


def change_phone_number(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()

    for flat in flats:
        phone_number = flat.owners_phonenumber
        flat.owner_pure_phone = get_correct_phone_number(phone_number)
        flat.save()


def get_correct_phone_number(phone_number):

    if not phone_number:
        return None

    number_info = phonenumbers.parse(phone_number, "RU")
    normal_number = phonenumbers.format_number(number_info, phonenumbers.PhoneNumberFormat.E164)

    try:
        phonenumbers.is_valid_number(normal_number)
        return normal_number
    except Exception:
        return None


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250502_1919'),
    ]

    operations = [
        migrations.RunPython(change_phone_number)
    ]
