# Generated by Django 2.2.24 on 2025-05-03 07:35

from django.db import migrations
import phonenumbers


def move_data_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all().iterator()

    for flat in flats:
        owner_name = flat.owner
        owners_phonenumber = flat.owners_phonenumber
        owner_pure_phone = get_correct_phone_number(owners_phonenumber)
        owner = Owner.objects.get_or_create(
            owner=owner_name,
            owners_phonenumber=owners_phonenumber,
            owner_pure_phone=owner_pure_phone
        )
        owner[0].flat_property.add(flat)


def get_correct_phone_number(phone_number):

    if not phone_number:
        return None

    try:
        number_info = phonenumbers.parse(phone_number, "RU")
        normal_number = phonenumbers.format_number(number_info, phonenumbers.PhoneNumberFormat.E164)

        if phonenumbers.is_valid_number(number_info):
            return normal_number
        else:
            return None

    except Exception:
        return None


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_owner'),
    ]

    operations = [
        migrations.RunPython(move_data_to_owner)
    ]
