# Generated by Django 2.2.24 on 2025-05-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20250503_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='property.Flat', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
