# Generated by Django 2.2.24 on 2025-05-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20250505_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
    ]
